create table if not exists public.letter_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in (
    'human_visit',
    'letter_opened',
    'slideshow_viewed',
    'music_played',
    'letter_finished'
  )),
  session_id text not null check (char_length(session_id) between 1 and 64),
  created_at timestamptz not null default now(),
  unique (session_id, event_name)
);

alter table public.letter_events enable row level security;

create index if not exists letter_events_created_at_idx
  on public.letter_events (created_at desc);
